### ISSUE TITLE
Export Control method so you can get to fd?

### ISSUE THREAD

**Issue by dwlnetnl** [mdlayher/socket#11]
I want to set a custom socket option through setsockopt, but the only exported method to help with this is SetsockoptInt which is not what I need. Instead of doing something specifically for setsockopt, I think it would be beneficial to provide access to the underlying file descriptor by adding a public Control method of some sorts in line with `syscall.RawConn`.

**Comment by mdlayher** [comment]
https://pkg.go.dev/github.com/mdlayher/socket#Conn.SyscallConn

Should provide exactly what you want, though I welcome PRs to add wrappers for new setsockopt and ioctl types since this is a syscall plumbing library.

**Comment by dwlnetnl** [comment]
Yeah using RawConn is indeed a solution. As it's a struct I have to pass I will have to resort to using the `unsafe` package and do some linker and pointer trickery. I don't think introducing `unsafe.Pointer` in public API is the right call for the package.
