### ISSUE TITLE
Missing error check in socket fallback path

### ISSUE THREAD

**Issue by tmthrgd** [mdlayher/socket#3]
The `unix.Socket` call in `EINVAL` or `EPROTONOSUPPORT` fallback path in `socket` is missing the error check:

https://github.com/mdlayher/socket/blob/7c9fcbcebf504a63e5d002868c514b6bb97708ba/conn.go#L197-L204

That means if `unix.Socket` fails with `EINVAL` or `EPROTONOSUPPORT` and then fails again, a `*Conn` will be returned referencing `fd=0` / `/dev/stdin`.

**Comment by mdlayher** [comment]
Thank you!
