### ISSUE TITLE
Add context.Context support

### ISSUE THREAD

**Issue by dwlnetnl** [mdlayher/socket#6]
I’ve noticed @mdlayher did a little experiment with a read context. Any thoughts on the topic?

**Comment by mdlayher** [comment]
I assume you were looking at https://github.com/mdlayher/socket/commit/dc31c6b944af0543e83c5392a6419a9780c105f8?

Truthfully I don't remember what I was working on here, but having context support to cancel nonblocking syscall waits makes sense to me. If you have a use case for it and can show that the code I have roughly does what you want, I'm happy to commit it to main.

**Comment by dwlnetnl** [comment]
Yes that's indeed the commit I was looking at. I'd like to extend the package with context support, so the package I'm working on can use the latest best practices- using contexts.

**Comment by dwlnetnl** [comment]
#8 looks good @mdlayher! I'm happy that I could contribute.

**Comment by mdlayher** [comment]
Thank you so much, I really appreciate it! I think there may be some extra room for context use in some of the long-blocking methods like Accept but this is a great start.

**Comment by dwlnetnl** [comment]
Yeah, I get what you're saying about Accept and that could be a great idea indeed.
